spring:
  application:
    name: StockApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockdb
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

# H2 Console configuration (optional)
  h2:
    console:
      enabled: true
      path: /h2-console

# Hibernate configuration
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: admin  # Default username
      password: password  # Default password
